---
abstract: 'AuthenSimple plugin for PlugAuth'
author:
  - 'Graham Ollis <plicease@cpan.org>'
build_requires:
  File::HomeDir: 0
  File::HomeDir::Test: 0
  File::Spec: 0
  Params::Validate: 0
  PlugAuth: 0
  Test::More: 0
  YAML: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.132661'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PlugAuth-Plugin-AuthenSimple
requires:
  Authen::Simple: 0
  PlugAuth::Role::Auth: 0
  PlugAuth::Role::Plugin: 0
  Role::Tiny: 0
  perl: 5.006
resources:
  bugtracker: https://github.com/plicease/plugauth-plugin-authensimple/issues
  homepage: http://perl.wdlabs.com/PlugAuth-Plugin-AuthenSimple/
  repository: git://github.com/plicease/plugauth-plugin-authensimple.git
version: 0.01
